### ISSUE TITLE
Fatal Error when doing ./flow aimeos:setup

### ISSUE THREAD

**Issue by ghost** [aimeos/aimeos-flow#11]
Hi,

just installed aimeos with composer and when getting the part with ./flow aimeos:setup --option=setup/default/demo:1 i got a fatal error:

PHP Fatal error:  Class 'Imagine\Image\ImageInterface' not found in /Users/kim/Sites/Neos-2.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Reflection/ReflectionService.php on line 1700
Execution of subprocess failed with exit code 255 without any further output.
(Please check your PHP error log for possible Fatal errors)

  Type: TYPO3\Flow\Core\Booting\Exception\SubProcessException
  Code: 1355480641
  File: Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php
  Line: 528

Running Neos 2.0 on local machine (Mac) and installation went smooth with all dependencies done via composer.

Any idea or have you had this error before.

Kind regards,

Kim Holberg

**Comment by aimeos** [comment]
The class/interface isn't one of Aimeos. There's another package that creates that error.

**Comment by ghost** [comment]
I understand but, i have now tried this on two separate installations which gives exactly same error. I follow your instructions very carefully.

Second time i did a composer update before - no problem. Then inserting your code in my composer.json file and then composer update again - then fatal error

It looks like it cannot find Class 'Imagine\Image\ImageInterface’ - how can i include that?

**Comment by aimeos** [comment]
Hm, very strange. Aimeos has no dependencies to Neos' Imagine\Image\ImageInterface and also doesn't use it. Do you have any other composer packages installed that are non-standard?

For a test, you could install the base Flow distribution in your environment and follow the steps how to install Aimeos. If the error occurs there too, it might be something in your environment. If not, there's something in your Neos installation that may cause the problem. Afterwards, you could try to set up a base Neos installation with Aimeos. Maybe we can get closer to the root cause this way.

**Comment by ghost** [comment]
issue resolved - i had a "require" too much in the composer.son file, which were overriding the first one.

**Comment by aimeos** [comment]
Great! :-)
